### ISSUE TITLE
Long-lived client object can cause "invalid baton" errors

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-client-ts#119]
If you have a long-lived client object, the server can start complaining about the baton:

```
 LibsqlError: SERVER_ERROR: Server returned HTTP status 400: Received an invalid baton
    at (node_modules/@libsql/client/lib-esm/hrana.js:257:15)
    at (node_modules/@libsql/client/lib-esm/hrana.js:182:36)
    at (node_modules/@libsql/client/lib-esm/hrana.js:184:12)
    at (node_modules/drizzle-orm/libsql/index.mjs:38:12)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:210:36) {
  code: 'SERVER_ERROR',
  rawCode: undefined,
  name: 'LibsqlError'
}
```

**Comment by txuanson** [comment]
Any update on this?

**Comment by yotam-haran** [comment]
I am using Turso with Drizzle on my backend, and have been running into this error quite frequently today. Is there any plan to address this?

**Comment by statusunknown418** [comment]
updates here? it seems to only happen sometimes

**Comment by garrettApproachableGeek** [comment]
We are seeing this error in production about every 2 days. We don't have long lived clients as each GCP Cloud Function creates it's own client. We are using a transaction in the section of code that throws `LibsqlError: SERVER_ERROR: Server returned HTTP status 400: Received an invalid baton`. 

`@libsql/client` version 0.5.6

```
const transaction = await client.transaction('write');
await transaction.execute({
   sql: 'INSERT INTO secret(key, value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=? WHERE key=?',
   args: [key, value, value, key]
});
await transaction.commit();
```

**Comment by rbestardpino** [comment]
Hey all. It is still happening on version 0.6.2. Did someone figure out a workaround? Not using transactions is not a real solution

**Comment by Fryuni** [comment]
Happens for every transaction from Vercel in our case

**Comment by luiz-gustavo-agostinho** [comment]
Running on Laravel

`php artisan migrate:fresh --seed` 

causes this error to happen after a while. Any solutions?

**Comment by PrinceBaghel258025** [comment]
Happens for many transaction when using libsql_experimental
