### ISSUE TITLE
The client does not work with bun

### ISSUE THREAD

**Issue by avinassh** [libsql/libsql-client-ts#85]
A user has reported that libsql fails with bun:

 ```
$ bunx drizzle-kit push:sqlite
[2.70ms] ".env"
No config path provided, using default path
Reading config file '/mnt/d/htmlcss/the-beth-stack/drizzle.config.ts'
drizzle-kit: v0.19.13
drizzle-orm: v0.28.6

43324 |       code;
43325 |       constructor(message, code, cause) {
43326 |         if (code !== void 0) {
43327 |           message = `${code}: ${message}`;
43328 |         }
43329 |         super(message, { cause });
            ^
LibsqlError: HRANA_WEBSOCKET_ERROR: Unexpected server response: 404
 code: "HRANA_WEBSOCKET_ERROR"

      at new LibsqlError (/mnt/d/htmlcss/the-beth-stack/node_modules/drizzle-kit/index.cjs:43329:8)
      at mapHranaError (/mnt/d/htmlcss/the-beth-stack/node_modules/drizzle-kit/index.cjs:48441:11)
      at /mnt/d/htmlcss/the-beth-stack/node_modules/drizzle-kit/index.cjs:48575:16
      at processTicksAndRejections (:1:2602)
error: "drizzle-kit" exited with code 1 (SIGHUP)
error: script "db:push" exited with code 1 (SIGHUP)
```

Another issue mentioned in the same thread about `fetch`

![image](https://github.com/libsql/libsql-client-ts/assets/640792/4d8956f2-3d46-49f2-a184-2e488ebdc77d)

[disucssion on discord](https://discord.com/channels/933071162680958986/1150465987230052432/1150465987230052432)

**Comment by arjunindia** [comment]
Thank you for opening this issue here as well ✨

**Comment by avinassh** [comment]
Closing as [0.3.3](https://github.com/libsql/libsql-client-ts/releases/tag/v0.3.3) fixed it
